services:
  postgres:
    image: postgres
    shm_size: '4gb'
    container_name: vibetravels-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: VibeTravels
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  VibeTravels:
    name: vibetravels-network

volumes:
  postgres:
    driver: local